### PR TITLE
[bugfix] Fix SSH private key path override bug

### LINKED ISSUE #2970: [BUG] SSH connector incorrectly overrides user-specified private key path when private_key_content is not provided
### What is version of KubeKey has the issue?

{"major":"4","minor":"0","gitVersion":"v4.0.3","gitCommit":"fd08c8caab8116f87810b5cde3313a7cbacc53fb","gitTreeState":"clean","buildDate":"2026-01-20T10:40:44Z","goVersion":"go1.25.0","compiler":"gc","platform":"linux/amd64"}

### What is your os environment?

ubuntu 24.04

### KubeKey config file

```yaml
apiVersion: core.kubekey.io/v1alpha1
kind: Inventory
metadata:
  name: my-cluster
hosts:
  - name: master-node
    ssh:
      host: 192.168.1.100
      port: 22
      user: root
      private_key: ~/.ssh/id_ed25519  # Custom key path
      # private_key_content:          # Not provided
```

### What happened

When configuring an SSH connection with a custom private key path (e.g., `~/.ssh/id_ed25519`) without providing `private_key_content`, the SSH connector incorrectly overrides the user-specified key path with the default `~/.ssh/id_rsa` path.

**Expected behavior**: The SSH connector should use the user-specified `~/.ssh/id_ed25519` key path.

**Actual behavior**: The SSH connector ignores the user-specified key path and defaults to `~/.ssh/id_rsa`, causing authentication failures when `id_rsa` doesn't exist or has different credentials.

### Root Cause

**File**: `pkg/connector/ssh_connector.go`
**Lines**: 86-95

The bug is on line 94 where the code incorrectly assigns to `keyParam` instead of `keycontentParam`:

```go
// Line 86-90: Correctly retrieves private_key path
keyParam, err := variable.StringVar(nil, hostVars, _const.VariableConnector, _const.VariableConnectorPrivateKey)
if err != nil {
    klog.V(4).Infof("ssh public key is empty, use: %s", defaultSSHPrivateKey)
    keyParam = defaultSSHPrivateKey  // ✓ Correct
}

// Line 91-95: BUG - incorrectly overrides keyParam instead of setting keycontentParam
keycontentParam, err := variable.StringVar(nil, hostVars, _const.VariableConnector, _const.VariableConnectorPrivateKeyContent)
if err != nil {
    klog.V(4).Infof("ssh public key is empty, use: %s", defaultSSHPrivateKey)
    keyParam = defaultSSHPrivateKey  // ✗ BUG: should set keycontentParam, not keyParam
}
```

### Impact

- **Affected Users**: All users specifying custom SSH key paths without providing `private_key_content`
- **Common Scenarios**:
  - Users preferring ed25519 keys (`~/.ssh/id_ed25519`)
  - Users with ECDSA keys (`~/.ssh/id_ecdsa`)
  - Users with custom key paths
- **Consequence**: Specified key path is silently ignored, leading to authentication failures

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tpiperatgod**
### What type of PR is this?
/kind bug

### What this PR does / why we need it:
This PR fixes a bug where custom SSH private key paths (e.g., `~/.ssh/id_ed25519`) were being incorrectly overridden by the default path (`~/.ssh/id_rsa`) when `private_key_content` was not provided in the inventory configuration.

**The Problem:**
- When users specified a custom `private_key` path in their inventory, the connector would still overwrite it with the default path if `private_key_content` was empty
- This made it impossible to use non-default SSH key files like `id_ed25519`, `id_ecdsa`, or keys in custom locations

**The Solution:**
- Implemented exclusive priority logic for SSH authentication methods:
  1. **Highest priority**: `private_key_content` (inline key content)
  2. **Second priority**: `private_key` (custom file path) - only used if `private_key_content` is empty
  3. **Fallback**: Default path (`~/.ssh/id_rsa`) - only used if both above are empty

**Impact:**
- Users can now specify custom SSH key paths that will be properly respected
- Backward compatibility maintained: existing configurations continue to work
- More flexible authentication options for diverse SSH key setups

### Which issue(s) this PR fixes:

Fixes #2970 

### Special notes for reviewers:
```
1. Key Change: Modified `setupSSHAuthMethods()` in pkg/connector/ssh_connector.go
   - Previously: Always set default path when private_key_content was empty
   - Now: Only set default path when BOTH private_key_content AND private_key are empty

2. Test Coverage: Added comprehensive test suite (pkg/connector/ssh_connector_test.go)
   - Tests all three priority scenarios
   - Verifies file existence checking logic
   - Validates fallback behavior

3. Backward Compatibility:
   - Existing configs with no private_key specified still default to ~/.ssh/id_rsa
   - Configs with private_key_content continue to work as before
   - New: Configs with custom private_key paths now work correctly

4. Code Quality:
   - 260 insertions, 7 deletions
   - Added detailed comments explaining the priority logic
   - No breaking changes to public APIs
```

### Does this PR introduced a user-facing change?

```release-note
Fixed bug where custom SSH private key paths were overridden by default path. Users can now specify custom key paths like ~/.ssh/id_ed25519 in their inventory configuration, and these paths will be properly respected when private_key_content is not provided.
```

### Additional documentation, usage docs, etc.:

```docs
None - This is a bug fix that makes existing documented behavior work correctly.
No additional documentation changes are needed.
```

### Files Changed
- `pkg/connector/ssh_connector.go` (modified) - Core fix implementation
- `pkg/connector/ssh_connector_test.go` (created) - Comprehensive test coverage

### Testing
The fix includes unit tests covering:
- Custom private key path specification
- Private key content takes priority over path
- Default path fallback when neither is specified
- File existence validation

### Example Usage

**Before (broken):**
```yaml
# inventory.yaml
hosts:
  - name: node1
    address: 192.168.1.10
    user: ubuntu
    private_key: ~/.ssh/id_ed25519  # This was ignored!
```

**After (fixed):**
```yaml
# inventory.yaml
hosts:
  - name: node1
    address: 192.168.1.10
    user: ubuntu
    private_key: ~/.ssh/id_ed25519  # Now properly respected!
```

### CODE REVIEW

File: pkg/connector/ssh_connector.go [hunk 1]
```diff
@@ -126,24 +126,38 @@ type sshConnector struct {
...
+			return errors.Wrapf(err, "failed to parse private key content")
 		}
 		auth = append(auth, ssh.PublicKeys(privateKey))
-	}
-	if _, err := os.Stat(c.PrivateKey); err == nil {
+		klog.V(4).InfoS("using private key content for authentication")
+	} else if c.PrivateKey != "" {
+		// Priority 2: Use ONLY PrivateKey path (if content not set)
+		if _, err := os.Stat(c.PrivateKey); err != nil {
+			return errors.Wrapf(err, "private key file not found: %s", c.PrivateKey)
```
Comment (will4j) [inline pkg/connector/ssh_connector.go:159]: c.PrivateKey will be default as `defaultSSHPrivateKey`, which is `~/.ssh/id_rsa`, if `~/.ssh/id_rsa` file not exists, this may cause task failed with `private key file not found`, event if `password` auth are provided.

better to only check private key existence if `c.PrivateKey` is not defaultSSHPrivateKey.

@tpiperatgod @redscholar

Comment (tpiperatgod) [reply pkg/connector/ssh_connector.go:159]: I got your point. How about this approach:

Scenario 1: Password-Only Authentication, succeeds using password authentication

```yaml
hosts:
  node1:
    connector:
      type: ssh
      host: 192.168.1.100
      user: root
      password: mypassword
      # No private_key specified, and default key path doesn't exist
```

Scenario 2: Default Key Exists, uses default key `~/.ssh/id_rsa` + password

```yaml
hosts:
  node1:
    connector:
      type: ssh
      host: 192.168.1.100
      user: root
      password: mypassword
      # No private_key specified, but default key path exists
```

Scenario 3: Explicit Custom Key, if file exists: Uses the specified key; otherwise fails immediately with clear error

```yaml
hosts:
  node1:
    connector:
      type: ssh
      host: 192.168.1.100
      user: root
      private_key: /custom/path/id_ed25519
```

Scenario 4: Key Content, uses the inline key content directly

```yaml
hosts:
  node1:
    connector:
      type: ssh
      host: 192.168.1.100
      user: root
      private_key_content: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmU...
        -----END OPENSSH PRIVATE KEY-----
```

Scenario 5: Multiple Auth Methods, tries key authentication first and fall back to password

```yaml
hosts:
  node1:
    connector:
      type: ssh
      host: 192.168.1.100
      user: root
      password: fallback_password
      private_key: ~/.ssh/id_ed25519
```
